Bump and use Debian

diff --git a/build/Dockerfile b/build/Dockerfile
--- a/build/Dockerfile
+++ b/build/Dockerfile
@@ -1,36 +1,22 @@
-FROM alpine as binary
+FROM debian:bullseye-slim as binary
 
-ARG VERSION=0.19.0.1
+ARG VERSION=0.20.0
 
 ENV FILENAME bitcoin-${VERSION}-x86_64-linux-gnu.tar.gz
 ENV DOWNLOAD_URL https://bitcoin.org/bin/bitcoin-core-${VERSION}/${FILENAME}
-ENV SHA256SUM 732cc96ae2e5e25603edf76b8c8af976fe518dd925f7e674710c6c8ee5189204
+ENV SHA256SUM 35ec10f87b6bc1e44fd9cd1157e5dfa483eaf14d7d9a9c274774539e7824c427
 
 ADD $DOWNLOAD_URL /$FILENAME
 RUN if [ x"$( sha256sum /${FILENAME} | awk '{print $1}' )" != x"${SHA256SUM}" ]; then \
-      rm -f /$FILENAME; \
-      echo "Checksum verification failed."; \
-      exit 1; \
-    else \
-      tar xzvf /$FILENAME; \
-      mv /bitcoin-${VERSION} /bitcoin; \
-    fi
+  rm -f /$FILENAME; \
+  echo "Checksum verification failed."; \
+  exit 1; \
+  else \
+  tar xzvf /$FILENAME; \
+  mv /bitcoin-${VERSION} /bitcoin; \
+  fi
 
-FROM alpine AS final
-
-ARG GLIBC_VERSION=2.30-r0
-
-RUN apk update \
-  && apk --no-cache add wget bash ca-certificates \
-  && wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub \
-  && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-${GLIBC_VERSION}.apk \
-  && wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/${GLIBC_VERSION}/glibc-bin-${GLIBC_VERSION}.apk \
-  && apk --no-cache add glibc-${GLIBC_VERSION}.apk \
-  && apk --no-cache add glibc-bin-${GLIBC_VERSION}.apk \
-  && rm -rf /glibc-${GLIBC_VERSION}.apk \
-  && rm -rf /glibc-bin-${GLIBC_VERSION}.apk \
-  && mkdir /root/.bitcoin \
-  && apk del wget ca-certificates
+FROM debian:bullseye-slim AS final
 
 EXPOSE 8332 8333 18332 18333 28332 28333
 
