Dockerfile improvements.

diff --git a/build/Dockerfile b/build/Dockerfile
--- a/build/Dockerfile
+++ b/build/Dockerfile
@@ -1,14 +1,20 @@
+# Based on https://github.com/jamesob/docker-bitcoind
 FROM alpine
-# 
 
 ARG VERSION=0.16.2
 ARG GLIBC_VERSION=2.27-r0
 
 ENV FILENAME bitcoin-${VERSION}-x86_64-linux-gnu.tar.gz
 ENV DOWNLOAD_URL https://bitcoin.org/bin/bitcoin-core-${VERSION}/${FILENAME}
+ENV SHA256SUM 71f217e30e98d5ccc1fb574b9499595e87e118e596278fad5507a7b84650859c
 
-# Some of this was unabashadly yanked from
-# https://github.com/szyhf/DIDockerfiles/blob/master/bitcoin/alpine/Dockerfile
+# Adding checksum for security
+ADD $DOWNLOAD_URL /$FILENAME
+RUN if [ x"$( sha256sum /${FILENAME} | awk '{print $1}' )" != x"${SHA256SUM}" ]; then \
+      rm -f /$FILENAME; \
+      echo "Checksum verification failed."; \
+      exit 1; \
+    fi
 
 RUN apk update \
   && apk --no-cache add wget tar bash ca-certificates \
@@ -19,12 +25,13 @@ RUN apk update \
   && apk --no-cache add glibc-bin-${GLIBC_VERSION}.apk \
   && rm -rf /glibc-${GLIBC_VERSION}.apk \
   && rm -rf /glibc-bin-${GLIBC_VERSION}.apk \
-  && wget $DOWNLOAD_URL \
-  && tar xzvf /bitcoin-${VERSION}-x86_64-linux-gnu.tar.gz \
+  && tar xzvf /$FILENAME \
   && mkdir /root/.bitcoin \
   && mv /bitcoin-${VERSION}/bin/* /usr/local/bin/ \
+  && rm /usr/local/bin/bitcoin-qt \
+  && rm /usr/local/bin/test_bitcoin \
   && rm -rf /bitcoin-${VERSION}/ \
-  && rm -rf /bitcoin-${VERSION}-x86_64-linux-gnu.tar.gz \
+  && rm -rf /$FILENAME \
   && apk del tar wget ca-certificates
 
 EXPOSE 8332 8333 18332 18333 28332 28333
